import { z } from 'zod';

export const siteConfigSchema = z.object({
  name: z.string(),
  descriptor: z.string(),
  tagline: z.string(),
  primaryCta: z.string(),
  email: z.string().email(),
  socials: z.object({
    instagram: z.string(),
    instagramMain: z.string(),
    sortMyScene: z.string(),
  }),
  palette: z.object({
    void: z.string(),
    onyx: z.string(),
    satin900: z.string(),
    satin700: z.string(),
    satin500: z.string(),
    vein: z.string(),
    gold900: z.string(),
    gold700: z.string(),
    gold500: z.string(),
    gold300: z.string(),
    gold100: z.string(),
    goldBright: z.string(),
    ivory: z.string(),
    ivoryDim: z.string(),
    diamond: z.string(),
    champagne: z.string(),
    confetti: z.string(),
    emberDeep: z.string(),
    ember: z.string(),
    emberHot: z.string(),
    drop: z.string(),
    dropDeep: z.string(),
    dropHi: z.string(),
    aegean: z.object({
      night: z.string(),
      aegean: z.string(),
      sky: z.string(),
      whitewash: z.string(),
      chrome: z.string(),
    }),
  }),
});

export type SiteConfig = z.infer<typeof siteConfigSchema>;

export const siteConfig: SiteConfig = {
  name: 'UNDERDOGS INNERCIRCLE',
  descriptor: 'The Private Gated Circle of Underdogs Entertainment',
  tagline: 'Different worlds. Same coin.',
  primaryCta: 'Request Your Coin',
  email: 'concierge@underdogs.in',
  socials: {
    instagram: 'https://instagram.com/underdogsinnercircle',
    instagramMain: 'https://instagram.com/underdogs_nagpur',
    sortMyScene: 'https://sortmyscene.com/p/underdogs-entertainment',
  },
  palette: {
    void: '#080706',
    onyx: '#0F0E0C',
    satin900: '#141310',
    satin700: '#211E19',
    satin500: '#38332B',
    vein: '#C8B08A',
    gold900: '#524332',
    gold700: '#8E7B62',
    gold500: '#A89271',
    gold300: '#C8B08A',
    gold100: '#EDE2D0',
    goldBright: '#EDE2D0',
    ivory: '#EDE2D0',
    ivoryDim: '#C4BCB0',
    diamond: '#EDE2D0',
    champagne: '#C8B08A',
    confetti: '#C8B08A',
    emberDeep: '#524332',
    ember: '#8E7B62',
    emberHot: '#eab673',
    drop: '#e32605',
    dropDeep: '#a01201',
    dropHi: '#f0421f',
    aegean: {
      night: '#14224a',
      aegean: '#2451a6',
      sky: '#8cbbe8',
      whitewash: '#f3efe6',
      chrome: '#d9dde3',
    },
  },
};
