import { z } from 'zod';

export const siteConfigSchema = z.object({
  name: z.string(),
  descriptor: z.string(),
  tagline: z.string(),
  primaryCta: z.string(),
  email: z.string().email(),
  socials: z.object({
    instagram: z.string(),
    instagramMain: z.string(),
    sortMyScene: z.string(),
  }),
  palette: z.object({
    void: z.string(),
    onyx: z.string(),
    satin900: z.string(),
    satin700: z.string(),
    satin500: z.string(),
    vein: z.string(),
    gold900: z.string(),
    gold700: z.string(),
    gold500: z.string(),
    gold300: z.string(),
    gold100: z.string(),
    goldBright: z.string(),
    ivory: z.string(),
    ivoryDim: z.string(),
    diamond: z.string(),
    champagne: z.string(),
    confetti: z.string(),
    emberDeep: z.string(),
    ember: z.string(),
    emberHot: z.string(),
    drop: z.string(),
    dropDeep: z.string(),
    dropHi: z.string(),
    aegean: z.object({
      night: z.string(),
      aegean: z.string(),
      sky: z.string(),
      whitewash: z.string(),
      chrome: z.string(),
    }),
  }),
});

export type SiteConfig = z.infer<typeof siteConfigSchema>;

export const siteConfig: SiteConfig = {
  name: 'UNDERDOGS INNERCIRCLE',
  descriptor: 'The Private Gated Circle of Underdogs Entertainment',
  tagline: 'Different worlds. Same coin.',
  primaryCta: 'Request Your Coin',
  email: 'concierge@underdogs.in',
  socials: {
    instagram: 'https://instagram.com/underdogsinnercircle',
    instagramMain: 'https://instagram.com/underdogs_nagpur',
    sortMyScene: 'https://sortmyscene.com/p/underdogs-entertainment',
  },
  palette: {
    void: '#050505',
    onyx: '#141414',
    satin900: '#23171c',
    satin700: '#342528',
    satin500: '#503731',
    vein: '#beb8b2',
    gold900: '#73572b',
    gold700: '#977947',
    gold500: '#b2955e',
    gold300: '#cbb074',
    gold100: '#f3e0ac',
    goldBright: '#f2d68f',
    ivory: '#ece1cf',
    ivoryDim: '#ded3c1',
    diamond: '#e3d8cf',
    champagne: '#e3bc95',
    confetti: '#edbf79',
    emberDeep: '#7d4b2d',
    ember: '#ae7144',
    emberHot: '#eab673',
    drop: '#e32605',
    dropDeep: '#a01201',
    dropHi: '#f0421f',
    aegean: {
      night: '#14224a',
      aegean: '#2451a6',
      sky: '#8cbbe8',
      whitewash: '#f3efe6',
      chrome: '#d9dde3',
    },
  },
};
